#Tarea 4.2 

create  database ClaseBD;
use ClaseBD;

CREATE TABLE infoClients (
Num_Cliente INT,
NombreCliente VARCHAR(50),
NombreCliente2 VARCHAR(50),
NombreCliente3 VARCHAR(50),
Condicion INT,
NoCteAnt VARCHAR(50),
Calle VARCHAR(50),
NoExterno VARCHAR(50),
Colonia VARCHAR(50),
EntreCalle VARCHAR(50),
CP INT,
yCalle VARCHAR(50),
Poblacion VARCHAR(50),
DescRegion VARCHAR(50),
Coord_X FLOAT(9),
Coord_Y FLOAT(9),
OrgVentas INT,
ORVComercial VARCHAR(6),
OFVComercial VARCHAR(6),
AreaVentas VARCHAR(6),
GpoVendedores VARCHAR(6),
Centro VARCHAR(6),
Canal VARCHAR(6),
DescCanal VARCHAR(50),
DescSegmento VARCHAR(20), 
DescCanalEst VARCHAR(20),
DescGEC VARCHAR(20),
DescGECVirtual VARCHAR(20),
DescValMet VARCHAR(20),
DescGpoCanal VARCHAR(50),
DescTpoCanal VARCHAR(50),
Persona VARCHAR(20),
ModalidadVentas VARCHAR(6),
Cadena VARCHAR(6),
BloqPedidos VARCHAR(6),
Legal VARCHAR(6),
Fe_alta VARCHAR(12),
CondPago VARCHAR(12),
ROUTE2 VARCHAR(12), 
Situacion VARCHAR(20)
);

CREATE TABLE dailySales (
Dia INT,
Num_Cliente INT,
SKU INT,
Cajas INT,
Htls FLOAT,
Income FLOAT,
Promotion FLOAT,
Bonificaciones FLOAT,
Ayudas FLOAT,
Amort FLOAT,
Revenue FLOAT,
COGS FLOAT,
LLOGS FLOAT,
FGP FLOAT
);


CREATE TABLE coldCapacity (
MonthIndex INT,
Num_Cliente INT,
Mes_Num INT, 
Capacidad INT,
Capacidad2 INT,
CapacidadMin INT, 
CapacidadMax INT,
TOTAL_ENFRIADORES INT,
Status_cap VARCHAR(20),
STATUS_cap2 VARCHAR(20)
);

CREATE TABLE catalogSKU (
material INT,
desc_material VARCHAR(60),
category_group INT,
desc_category_group VARCHAR(60),
category INT,
desc_category VARCHAR(60),
segment INT,
desc_segment VARCHAR(60),
alcohol_content INT,
desc_alcohol_content VARCHAR(60),
bwp_role INT,
desc_bwp_role VARCHAR(60),
brand_group INT, 
desc_brand_group VARCHAR(60),
brand VARCHAR(20),
desc_brand VARCHAR(60),
line_ext VARCHAR(60),
desc_line_ext VARCHAR(60),
primary_pack_group INT, 
desc_primary_pack_group VARCHAR(60),
primary_pack_type INT, 
desc_primaty_pack_type VARCHAR(60),
returnability INT, 
desc_returnability VARCHAR(60),
hmex_pack_group INT,
desc_hmex_pack_group VARCHAR(60),
pack_size INT, 
desc_pack_size VARCHAR(60),
multipack INT, 
desc_multipack VARCHAR(60),
innovation INT,
desc_innovation VARCHAR(60),
price_segment INT,
desc_price_segment VARCHAR(60),
estatus VARCHAR(60),
capacidad_ml INT,
cantidad  INT,
total_ml INT,
descontinuado VARCHAR(10),
assort_presentacion VARCHAR(60)
  );